# Generated by Django 4.1.1 on 2022-09-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitcoinAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='currency',
            field=models.CharField(default='inr', max_length=50),
        ),
    ]
