# Generated by Django 4.1.1 on 2022-09-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BitcoinAPI', '0002_bitcoin_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitcoin',
            old_name='timestamp',
            new_name='created_on',
        ),
    ]
